### ISSUE TITLE
ContentType specific screens for easier customization

### ISSUE THREAD

**Issue by marcovandeveen** [jwplayer/ott-web-app#89]
Goal
- Easily add custom screen layouts to the web app, without impacting the standards screens

Solution 
- Each media item can be linked with contentType
- App config contains contentType screen mapping
- Screens can be added by dropping screen file  + scss in a [screens folder](https://github.com/jwplayer/ott-web-app/tree/develop/src/screens)
- Opening a media item opens the associated screen
- Default screen is 'movie' if no contentType is set

Adding custom screen

- Drop a screen file  + scss in a [screens folder](https://github.com/jwplayer/ott-web-app/tree/develop/src/screens)
- Build
- Link contentType to screen in app config

**Comment by budzworthy** [comment]
I am onboard with the basic concept. We may want to consider designing a full fledged plugable architecture to support this as well as making other customizations easier.

Probably no need to involve the app config.  If there is a build step to add the screens, we might as well define the linked content types there, then there are fewer moving pieces.

See also #54 and #27

**Comment by ChristiaanScheermeijer** [comment]
I agree with @dbudzins, we should do the contentType->screen mapping in the code. This makes it easier to compile and test since it won't build if the screen contains errors.

@marcovandeveen I've some additional questions for this feature:

**How to handle series (that are currently still linking media items)?**

TV Series are a bit different since we link the user to an URL composed via custom params from the linking media item. Do we keep this mechanism intact so contentType only works for "regular" media items a.k.a. Movies or do we want to leverage this mechanism to separate Movies from Series as well?

E.g.

ContentType: Series -> screens/Series/Series.tsx
ContentType: Movie (or empty) -> screens/Movie/Movie.tsx

The downside of the above is that the routing is different in Series, so to make this generic, we need to either have a single media route that handles everything or have a different mapping to determine which media items are series. This based on `contentType: Series` won't work with different series types. I.e. Vlog, Concert, ..?

We can also consider refactoring live channels to use this route as well.
